### ISSUE TITLE
PermissionError: Forbidden

### ISSUE THREAD

**Issue by AndreAdemollo** [OmbreaPV/pySTICS#2]
When running the example notebook `run_simulation.ipynb` after deleting the `.csv` files in the `meteo` folder, I get the the following error:
```
PermissionError: Forbidden
```

I think the error occurs because the S3 bucket read when generating the `.csv` for the precipitation data is not public. Is this bucket yours or is it ERA5's? How can I download the precipitation data for myself?

What I wanted to do was use this software to simulate locations and dates different from the ones in the example. Can you help me with that?

**Comment by etienneperez** [comment]
Hi AndreAdemollo,

Sorry for the late answer.

A new version will be released in the next months, we have chosen to remove the weather generation feature from this repo. You'll have to give a weather file as input, generated on your own. Sample weather files will be available.

Etienne

**Comment by pasquierjb** [comment]
Dear @AndreAdemollo We released a new version. Please test it out and let us know if you get some troubles generating a weather file.
